zookeeper:
        image: 'jplock/zookeeper:3.4.6'
        ports:
          - '2181:2181'
kafka:
        image: 'ches/kafka'
        links:
          - zookeeper:zookeeper
        ports:
          - "9092:9092"
